package exception;

public class Try {
	public static void main(String[] args) {
		System.out.println("Initialized");
		int a  = 10;
		int b = 0;
		int c = a/b;
		System.out.println(c);
		System.out.println("Finalised");
	}

}
